artifacts_root: artifacts

data_ingestion: 
 root_dir: artifacts/data_ingestion
 source_url: https://github.com/venkatmv41/End-to-End-ML-project-with-ML-flow/raw/refs/heads/main/winequality-data.zip
 local_data_file: artifacts/data_ingestion/data.zip
 unzip_dir: artifacts/data_ingestion
